title: 'Haight Ashbury & Haight Ashbury Free Clinic Archives'
author:
  name: 'Dr. Dave'
  email: joe@test.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Haight Ashbury &amp; Haight Ashbury Free Clinic Archives'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
